version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always

  admin:
    build: ./admin
    ports:
      - "5174:80"
    env_file:
      - ./admin/.env
    depends_on:
      - backend
    restart: always
